version: '3'

services:
  email_model:
    build:
      context: ./Backend
      dockerfile: Dockerfile_app3
    ports:
      - "5001:5000"
    networks:
      - my_network

  sms_model:
    build:
      context: ./Backend
      dockerfile: Dockerfile_app2
    ports:
      - "5002:8080"
    networks:
      - my_network

  url_model:
    build:
      context: ./Backend
      dockerfile: Dockerfile_app3
    ports:
      - "5003:8888"
    networks:
      - my_network

  api:
    build:
      context: ./Backend
      dockerfile: Dockerfile_app3
    ports:
      - "5003:8888"
    depends_on:
      - mongo
    networks:
      - my_network

  client:
    build:
      context: ./Frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - my_network

  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    networks:
      - my_network

networks:
  my_network:
