version: '3'

services:
  email_model:
    build:
      context: ./Backend
      dockerfile: Dockerfile_app1
    ports:
      - "5000:5000"
    networks:
      - my_network

  sms_model:
    build:
      context: ./Backend
      dockerfile: Dockerfile_app2
    ports:
      - "8080:8080"
    networks:
      - my_network

  url_model:
    build:
      context: ./Backend
      dockerfile: Dockerfile_app3
    ports:
      - "8888:8888"
    networks:
      - my_network

  api:
    build:
      context: ./Frontend/Server
      dockerfile: Dockerfile_app3
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - my_network

  client:
    build:
      context: ./Frontend
    ports:
      - "5173:5173"
    depends_on:
      - api
    networks:
      - my_network

  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    networks:
      - my_network
    volumes:
      - /path/on/host:/data/db

networks:
  my_network:
